AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    aws-cnf-attributes-macro

    SAM Template for aws-cnf-attributes-macro

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3

Resources:
    Macro:
        Type: AWS::CloudFormation::Macro
        Properties:
            Name: CnfAttributesMacro
            FunctionName: !GetAtt CnfAttributesMacroFunction.Arn

    CnfAttributesMacroFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: cnf_attributes_macro/
            Handler: app.lambda_handler
            Runtime: python3.7

Outputs:
    CnfAttributesMacroFunction:
        Description: "Hello World Lambda Function ARN"
        Value: !GetAtt CnfAttributesMacroFunction.Arn
